export const LABEL = {
  LOGIN: 'Sign in',
  HERO_SECTION1: 'First visit to European Wax Center?',
  HERO_SECTION2: 'Get your first wax on us!',
  EXPLORE_TREATMENT: 'Explore Treatments',
  VIEW_ALL: 'View All',
  VIEW_LESS: 'View Less',
  LEARN_ABOUT_US: 'Learn About Us',
  WHAT_TO_EXPECT: 'What to Expect on your first visit',
  FAQ: `FAQ's`,
  SIGN_DETAILS: 'Sign up for deals',
  POPULAR_GIFTS: 'Popular Gifts',
  LEARN_MORE: 'Learn More',
  ENTER_MOBILE_NUMBER: 'Please enter your mobile number to login',
  SEND_CODE: 'Send Code',
  VERIFY_CODE: 'Verify Code',
  CODE_MESSAGE: 'Confirm code to continue',
  BOOK_AN_APPOINTMENT: 'Book an Appointment',
  APPOINTMENT_CONFIRM: 'Appointment confirmed',
  OTP_SUCCESS: 'OTP sent successfully',
  OTP_VERIFY_SUCCESS: 'OTP verified successfully',
  OTP_VERIFY_FAILED: 'OTP verification failed, Please enter a valid OTP',
  OTP_VERIFY_TIMING: 'Maximum number of attempts exceeded, please resend OTP',
  CHOOSE_LOCATION: 'Choose a location',
  CHANGE_LOCATION: 'Change Location',
  SELECTED_TREATMENTS: 'Selected Treatments',
  MORE_FROM_LOCATION: 'More from this location',
  SPECIALITIES: 'Specialities',
  ANY_TIME: 'Any Time',
  ANY_SPECIALIST: 'Any Specialist',
  ANY: 'Any',
  NO_SPECIALIST_AVAILABLE: 'No specialists available currently.',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL_ADDRESS: 'Email address',
  PHONE_NUMBER: '1-847-926-9890',
  CHECK_BOX_DETAIL: 'Sign up for appointment reminders, tips, and EWC marketing. Additional terms and conditions apply.',
  BEFORE_YOUR_APPOINTMENT: 'Before your appointment',
  CONFIRM_CONTACT_DETAILS: 'Confirm your contact details',
  CONFIRM_DETAILS: 'Confirm Details',
  APPOINTMENT_BEGINS: 'Your appointment begins in',
  QUICK_BOOK: 'Quick Book',
  FINISH_BOOKING: 'Finish Booking',
  SELECT: 'Select',
  REMOVE: 'Remove',
  CONFIRM_BOOKING_LOGIN_MESSAGE: 'Confirm a phone number to reserve your booking',
  PLEASE_SELEECT_SERVICE: 'Please select a service to continue',
  YOUR_UPCOMING_APPOINTMENT: 'Your upcoming visit',
  BOOKNOW: 'Book Now',
  YOUR_DETAILS: 'Your Details',
  UPDATE_DETAILS: 'Update Details',
  TREATMENTS: 'treatments',
  ADD_TO_CART: 'Add to Cart',
  CHOOSE_A_LOCATION: 'Choose a location to get started',
  ACCOUNT_UPDATE_SUCCESS: 'Your account updated successfully',
  YOUR_WAX_PASS: 'Your Wax Pass',
  VALID_AT: ' Valid at',
};
