export const API_BASE_URL = "https://ewc.meevoqa.com/onlinebooking/api/"
export const INITIATE_SESSION = 'ob/initializeTenant?tenantId=20'
export const INITIATE_SESSION_19 = 'ob/initializeTenant?tenantId=20'
export const SERVICE_CATEGORY = 'ob/ServiceCategory/List'
export const SERVICE_CATEGORY_DETAILS = 'ob/service/list'
export const LOGIN = 'ob/otp'
export const OPT_VERIFICATION = 'auth/otp?locationId='
export const SERVICE_CATEGORY_LIST = 'ob/servicecategory/list'
export const SERVICE_CATEGORY_DETAILS_BY_ID = 'ewc/service/list?serviceCategoryId='
export const GET_SERVICE_SUB_CATEGORY = "ob/ServiceCategory/"
export const SERVICE_LIST_BY_CATEGORY_AND_SUBCATEGORY = "ewc/Service/List"
export const GET_EMPLOYEE = "ob/Employee/Search"
export const SCAN_FOR_OPENINGS = "ob/scanforopenings"
export const LOCATION_ACCESS = 'ob/LocationAccess/List?moduleIds=2212'
export const SETLOCATION = 'ob/Session'
export const APPOINTMENT_BOOKING = 'ob/appointment'
export const GETFUTUREAPPOINTMENTS = 'ob/AppointmentService/List'
export const CLIENT_UPDATE = 'ob/Client'